[package]
name = "nounours"
version = "0.1.0"
edition = "2021"
description = "Minimal Linux sandbox using Landlock"

[dependencies]
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
serde = { version = "1", features = ["derive"] }
toml_edit = { version = "0.22", features = ["serde"] }
landlock = "0.4"
